---
services:
  s3-ninja:
    #8.4.0 has no code changes only updates,
    # and does not come in arm64 version. let's stay on 8.3.3
    image: scireum/s3-ninja:8.3.3
    container_name: s3-ninja
    networks:
      - tfds-network
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ${TFDS_S3NINJA_DATA_DIR}:/home/sirius/data

networks:
  tfds-network:
    name: tfds-network
    external: true
