repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        stages: [pre-commit, pre-push]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=120]
        stages: [pre-commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]  # example

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # check https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        stages: [pre-commit, pre-push]


  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1  # Or pin a specific commit SHA
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:

    -   id: nbqa-black
        args: [--line-length=120]  # Optional: match your Black config
        stages: [pre-commit, pre-push]

    -   id: nbqa-ruff
        additional_dependencies: [ruff]
        stages: [pre-commit, pre-push]

    -   id: nbqa-isort
        args: [--profile=black]
        stages: [pre-commit, pre-push]

    -   id: nbqa-mypy
        args: [
            '--ignore-missing-imports',
            '--follow-imports=silent'
        ]
        stages: [pre-commit, pre-push]

    -   id: nbqa-pyupgrade
        args: [--py38-plus]  # Set to your minimum Python version
        stages: [pre-commit, pre-push]
