[tool.pytest.ini_options]
norecursedirs = [
    "tfds",
    "the-free-data-stack",
    "pipe-dreams"
]

[tool.isort]
profile = "black"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.16.1"
pytest = "^8.4.0"
ruff = "^0.11.13"
pre-commit = "^4.2.0"

[project]
name = "the-free-data-stack"
version = "0.1.0"
description = "FreeDS plugin repo"
authors = [
    {name = "freeds@jensbox.se"}
]
license = {text = "GNU GENERAL PUBLIC LICENSE v3"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
