[project]
name = "the-free-data-stack"
version = "0.1.0"
description = "freeds plugin repo"
authors = [
    {name = "freeds@jensbox.se"}
]
license = {text = "GNU GENERAL PUBLIC LICENSE v3"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "cowsay (>=6.1,<7.0)",
    "freeds @ file:///Users/jens/src/FreeDS"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry]
packages = [
    # actually this is not needed, but poetry needs something to install or you have to put the --no-root argument allt he time.
    # let in tinstall this. no harm...
    { include = "app", from = "freeds-config" }
]

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.16.1"
pytest = "^8.4.0"
ruff = "^0.11.13"
pre-commit = "^4.2.0"

[tool.poetry.dependencies]
freeds = {develop = true}

[tool.mypy]
python_version = "3.11"
strict = true


[[tool.mypy.overrides]]
module = "tests.*"
disable_error_code = ["no-untyped-def"]

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true


[tool.pytest.ini_options]
norecursedirs = [
    "tfds",
    "the-free-data-stack",
    "pipe-dreams"
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
ignore-init-module-imports = true
