# FROM bitnami/spark:3.5.3-debian-12-r3
FROM bitnami/spark:3.4.1-debian-11-r88


WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

USER root
RUN mkdir -p /opt/tfds/data && chown 1001 /opt/tfds/data
# whoami in a running docker revealed the userid to be 1001
USER 1001
