---
services:
  book-runner:
    container_name: book-runner
    hostname: book-runner
    build: .
    volumes:
      - /tmp/logs/book-runner:/tmp/logs
      - /tmp/notebooks:/tmp/notebooks
      - /tmp/output_notebooks:/tmp/output_notebooks
    networks:
      - tfds-network

networks:
  tfds-network:
    name: tfds-network
    external: true
