---
services:
  book-runner:
    image: tfds/papermill-base:${TFDS_VERSION}
    container_name: papermill-base
    environment:
      - TFDS_CONFIG_URL:"http://tfds-config:8005"
    networks:
      - tfds-network

networks:
  tfds-network:
    external: true  # Use the existing tfds-network