---
services:
  book_runner:
    image: tfds/papermill-base:${TFDS_VERSION}
    container_name: papermill-base
    volumes:
      - /tmp/logs/book-runner:/tmp/logs
      - /tmp/notebooks:/tmp/notebooks
      - /tmp/output_notebooks:/tmp/output_notebooks
