---
services:
  base:
    build: .
    container_name: papermill
    environment:
      TFDS_CONFIG_URL: ${TFDS_CONFIG_URL}
    networks:
      - tfds-network

  debug:
    build: .
    container_name: papermilldbg
    environment:
      TFDS_CONFIG_URL: ${TFDS_CONFIG_URL}
    networks:
      - tfds-network
    volumes:
      - .:/app

networks:
  tfds-network:
    external: true  # Use the existing tfds-network