spark.app.name                          WhenDoIGetToSparkMyWay
spark.master                            spark://spark-master:7077


spark.driver.extraClassPath             /opt/tfds/spark/jars/*
spark.executor.extraClassPath           /opt/tfds/spark/jars/*
# delta
spark.sql.catalog.spark_catalog         org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.extensions                    io.delta.sql.DeltaSparkSessionExtension

# there's no OSS catalog that works perfectly with delta. Hive spits out a lot of warnings about schema mergem but according to chatGPT and as we see, it all still works.
# these options are to make spark use a local derby database located in the mounted data directory. So, it will survive spark restarts and recreated dockers.
# I could not get the catalog to work while configured to use s3, local disk it is. data is still on s3.

# s3 configs
spark.hadoop.fs.s3a.endpoint            http://s3-minio:9000
# path.style.access seems necessary for using minio
spark.hadoop.fs.s3a.path.style.access   true
# this makes the delta tables go to s3
spark.sql.warehouse.dir                 s3a://dwh/warehouse/
# default is 200 partitions, which apparently is a bit high for a local setup
spark.sql.shuffle.partitions            12
# the wikipedia pageview dataset would not go through on default level. we need a bit more memory.
spark.executor.memory                   2g


spark.sql.catalogImplementation                          hive
spark.hadoop.javax.jdo.option.ConnectionURL             jdbc:postgresql://postgres:5432/spark_metastore
spark.hadoop.javax.jdo.option.ConnectionDriverName      org.postgresql.Driver
spark.hadoop.javax.jdo.option.ConnectionUserName        airflow
spark.hadoop.javax.jdo.option.ConnectionPassword        airflow
spark.hadoop.datanucleus.schema.autoCreateAll           true

spark.hadoop.hive.metastore.db.type                     postgresql
spark.hadoop.hive.metastore.db.uri                      jdbc:postgresql://postgres:5432/spark_metastore
spark.hadoop.hive.metastore.db.username                 airflow
spark.hadoop.hive.metastore.db.password                 airflow

spark.hadoop.hive.metastore.warehouse.dir               s3a://dwh/warehouse/
spark.hadoop.hive.metastore.db.driver                   org.postgresql.Driver
spark.hadoop.hive.metastore.cache.size                  1000  # Optional: Increase cache size if needed
spark.hadoop.hive.metastore.schema.verification         true    # Optional: To check schema validity during startup
spark.signal.config.value                               custom_config_file_found


# spark.sql.catalogImplementation         hive
# spark.hadoop.javax.jdo.option.ConnectionURL jdbc:derby:/opt/tfds/data/spark/metastore/metastore_db;create=true
# spark.hadoop.javax.jdo.option.ConnectionDriverName org.apache.derby.jdbc.EmbeddedDriver
# spark.jars                              /opt/tfds/spark/jars/*.jar
