services:
  api:
    build: .
    image: freeds/freeds-config:latest
    container_name: freeds-config
    expose:
      - 8005
    ports:
      - "127.0.0.1:8005:8005"
    environment:
      - FLASK_ENV=development
      - FDS_ROOT_PATH=/opt/freeds
      - FDS_CONFIGS_PATH=/opt/freeds/config/configs
      - FDS_LOCALS_PATH=/opt/freeds/config/locals
    volumes:
      - ${FDS_CONFIGS_PATH}:/opt/freeds/config/configs
      - ${FDS_LOCALS_PATH}:/opt/freeds/config/locals
    networks:
      - freeds-network

networks:
  freeds-network:
    name: freeds-network
    external: true
