services:
  api:
    build: .
    image: freeds/freeds-config:latest
    container_name: freeds-config
    expose:
      - 8005
    ports:
      - "127.0.0.1:8005:8005"
    environment:
      - FLASK_ENV=development
      - FREEDS_ROOT_PATH=/opt/freeds
    volumes:
      - ${FREEDS_ROOT_PATH}/freeds-config/configs:/opt/freeds/configs
      - ${FREEDS_ROOT_PATH}/local_configs:/opt/freeds/locals
    networks:
      - freeds-network

networks:
  freeds-network:
    name: freeds-network
    external: true
