services:
  api:
    build: .
    # image: tfds/tfds-config
    container_name: tfds-config
    expose:
      - 8005
    ports:
      - "127.0.0.1:8005:8005"
    environment:
      - FLASK_ENV=development
    volumes:
      - /opt/tfds/config:/opt/tfds/config
      - /opt/tfds/secrets:/opt/tfds/secrets
    networks:
      - tfds-network

networks:
  tfds-network:
    name: tfds-network
    external: true
