---
services:
  s3-minio:
    image: quay.io/minio/minio
    container_name: s3-minio
    networks:
      - freeds-network
    expose:
      - 9900
    ports:
      - "127.0.0.1:9900:9900"
      - "127.0.0.1:8006:8006"
    volumes:
      - "${TFDS_MINIO_DATA_DIR}:/data"
    environment:
      - MINIO_ROOT_USER=${TFDS_MINIO_USER}
      - MINIO_ROOT_PASSWORD=${TFDS_MINIO_PASSWORD}
    # use our mounted /data for storage and serve the web ui on port 8006
    command: server /data --console-address ":8006" --address :9900


networks:
  freeds-network:
    name: freeds-network
    external: true
