---
services:
  base:
    build: .
    image: freeds/jupyter-spark:latest
    container_name: jupyter-spark
    environment:
      FREEDS_CONFIG_URL: ${FREEDS_CONFIG_URL}
    ports:
      - "127.0.0.1:8888:8888"
    networks:
      freeds-network:
    command: /home/spark/.local/bin/jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''

networks:
  freeds-network:
    name: freeds-network
    external: true
