services:
  polaris:
    image: apache/polaris:1.0.1-incubating
    container_name: polaris
    ports:
      - "8181:8181"
    environment:
      # Tell Polaris which catalogs exist
      - POLARIS_CATALOGS=freeds_catalog

      # Configure the 'freeds_catalog' catalog
      - POLARIS_CATALOG_FREEDS_CATALOG_WAREHOUSE=file:///tmp/polaris-warehouse
      - POLARIS_CATALOG_FREEDS_CATALOG_IO_IMPL=org.apache.iceberg.filesystem.DefaultFileIO

      - POLARIS_CATALOG_FREEDS_CATALOG_WAREHOUSE=s3a://dwh/warehouse/
      - POLARIS_CATALOG_FREEDS_CATALOG_IO_IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - POLARIS_CATALOG_FREEDS_CATALOG_S3_ENDPOINT=http://s3-minio:9900
      - POLARIS_CATALOG_FREEDS_CATALOG_S3_ACCESS_KEY=${FREEDS_S3_ACCESS_KEY}
      - POLARIS_CATALOG_FREEDS_CATALOG_S3_SECRET_KEY=${FREEDS_S3_SECRET_KEY}

    networks:
      - freeds-network

networks:
  freeds-network:
    name: freeds-network
    external: true