services:
  devpi:
    build: .
    container_name: devpi

    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - ${FREEDS_ROOT_PATH}/local-pypi:/data
    command: devpi-server --host 0.0.0.0 --port 8008 --serverdir /data
    restart: unless-stopped
    networks:
      - freeds-network

networks:
  freeds-network:
    external: true  # Use the existing freeds-network