---

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${FDS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FDS_POSTGRES_PASSWORD}
    volumes:
      - ${FDS_POSTGRES_DATADIR}:/var/lib/postgresql/data
      # - ${FDS_POSTGRES_PATH}/init:/docker-entrypoint-initdb.d
    networks:
      - freeds-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${FDS_POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s

networks:
  freeds-network:
    name: freeds-network
    external: true
