plugin:
  resources:
    admin_user:
      type: AdminAccount
      description: Username and password for postgres administrator

    listening_port:
      type: KnownPort
      description: postgres listening port.
      params:
        number: 5432

    data_dir:
      type: DataDir
      description: Directory for postgres database files
