services:
  redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: redis
    networks:
      - freeds-network
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    expose:
      - 5540
    ports:
      - "127.0.0.1:${FDS_REDIS_UI_PORT_REDISINSIGHT}:5540"
    volumes:
      - ${FDS_REDIS_DATADIR_REDISINSIGHT}:/data
    networks:
      - freeds-network

networks:
  freeds-network:
    name: freeds-network
    external: true